### ISSUE TITLE
Use higher quality graphics

### ISSUE THREAD

**Issue by bitcoinx2** [titcoin/titcoin.github.io#1]
The background image and logo should be displayed with an adequate resolution, at least on systems that support it. Most modern web pages use high-res images nowadays.

Preferably all used images should be stored in the "graphics" repository at https://github.com/titcoin/graphics and be referred to from there, to support creative use (having a central location for images makes it easier to find them), to help organizing project artwork and to make the actual web development repository smaller.

**Comment by ghost** [comment]
used a higher resolution image as a background. erotica.jpg

**Comment by bitcoinx2** [comment]
Thanks, you could instead also directly refer to the stored image like this: https://raw.githubusercontent.com/titcoin/graphics/master/contrib/erotica-girl1-1920x1280.jpg

This was the original idea (see above). ;) Thoughts?

Please also update the logo in the top left. Btw. both of these things were already solved in the `use-graphics-repo` branch, maybe you could just review it and merge it, or explain where you disagree with it? :)

**Comment by ghost** [comment]
The files we use on the website are now in one location. The erotica.jpg is a copy of the original. We don't need to use the absolute path for this. I will do the logo next.

**Comment by ghost** [comment]
There is usually some misunderstanding between the size of an image and its quality. The higher the resolution, the higher the size of the file (in MB). Bringing down an image in resolution helps enormously in bring down the file size.
Changing a high resolution in pixel-size does nothing for the file size. 
Example; a 1920x1280 file could be show in a 125x125 pixel box but would still be 12MB

The marging between excellent/good enough/bad is highly subjective. 

In the old days speed was depended upon file size more than it is now. We all(?) remember images being loaded line by line on a website. Those days are probably over.

For the logo; there is no difference between the 2 files I have got only but pixel size.
