### ISSUE TITLE
Download buttons

### ISSUE THREAD

**Issue by bitcoinx2** [titcoin/titcoin.github.io#2]
Should have easy to find download buttons at the top of the page for all available download options (currently a Windows binary and getting the source from Github).

**Comment by ghost** [comment]
Where does this button point to? the zip or the URL? If there are more wallets you want more buttons?

**Comment by ghost** [comment]
added a download button

**Comment by bitcoinx2** [comment]
Ok. Maybe we can use a more flat design button with round corners, similar to these? https://www.kisspng.com/png-button-download-flat-design-icon-behind-the-androi-87511/ And the color should match the color of the Titcoin logo.

One button is probably enough because the link https://github.com/titcoin/titcoin/releases/tag/v0.16.3-titcoin also has an option to download the source as ZIP, which is the preferred download method for Linux users anyway.

**Comment by ghost** [comment]
The Titcoin logo has 2 colors. You prefer the light or the dark orange for the button?

**Comment by ghost** [comment]
Changed the Download Button. Used the lighter orange from the logo wich is funny enough named logo-red ;-)
