### ISSUE TITLE
Support semantic HTML lists

### ISSUE THREAD

**Issue by bitcoinx2** [titcoin/titcoin.github.io#3]
Lists should be written as HTML lists (`<ul>`) and not manually using asterisks (`*`) and `<br>`

This has a lot of advantages, e.g. when using source code editors or for search engines. See https://www.lifewire.com/why-use-semantic-html-3468271 for more info.

Currently text written in lists has a different font than the main text.

**Comment by ghost** [comment]
solved by changing style.css
