### ISSUE TITLE
Use relative path for background image

### ISSUE THREAD

**Issue by bitcoinx2** [titcoin/titcoin.github.io#4]
Referencing the background image as `background: url(/header-bg.jpg)` in https://github.com/titcoin/titcoin.github.io/blob/master/style.css#L77 makes my browser not display the image when opening a local version of the site after cloning the repo. Removing the slash ("/") solves the issue.

Is there a fundamental reason for referencing the file from the root of the host system (/ is the root) instead of relatively from the current directory?

**Comment by ghost** [comment]
there is a difference between the "/" in Unix and in HTML. It all depends on where the actual root is. On larger websites we normally use folders for css files and images. Github is different because of the repositories. On simple website like ours no need to change.

**Comment by bitcoinx2** [comment]
Well in the current version it just doesn't display the image when opening a local copy of the site. So there would be at least a small benefit of changing it. ;) What would be reasons _against_ using a relative path here?

**Comment by ghost** [comment]
you have a local copy on a PC/laptop? Than things are different ;-)
