### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by bitcoinx2** [titcoin/titcoin.github.io#5]
Should have a favicon :)

**Comment by ghost** [comment]
favicon is overrated. But if you can find one I will put it in.

**Comment by bitcoinx2** [comment]
Not sure if this one would work? It's the Windows icon used in the wallet. https://raw.githubusercontent.com/titcoin/titcoin/master/src/qt/res/icons/titcoin.ico I can make a different one if it doesn't work (just using GIMP).

**Comment by ghost** [comment]
Inserted the favicon in the website
